SteamNexus/Areas/Administrator/Controllers/GamesManagementController.cs
using HtmlAgilityPack;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using SteamNexus.Data;
using SteamNexus.Models;
using SteamNexus.ViewModels.Game;
using System.Text.RegularExpressions;

namespace SteamNexus.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class GamesManagementController : Controller
    {
        private readonly SteamNexusDbContext _context;

        public GamesManagementController(SteamNexusDbContext context)
        {
            _context = context;
        }

        //GameAJAX設定
        private async Task<DetailsViewModel> GetViewModel(int id)
        {
            var game = await _context.Games
                .FirstOrDefaultAsync(m => m.GameId == id);

            if (game == null)
            {
                return null; // 或者根據您的需求返回其他值
            }

            return new DetailsViewModel
            {
                GameId = id,
                AppId = game.AppId,
                Name = game.Name,
                OriginalPrice = game.OriginalPrice,
                CurrentPrice = game.CurrentPrice,
                LowestPrice = game.LowestPrice,
                AgeRating = game.AgeRating,
                Comment = game.Comment,
                CommentNum = game.CommentNum,
                ReleaseDate = game.ReleaseDate,
                Publisher = game.Publisher,
                Description = game.Description,
                Players = game.Players,
                PeakPlayers = game.PeakPlayers,
                ImagePath = game.ImagePath,
                VideoPath = game.VideoPath
            };
        }


        [HttpGet]
        public IActionResult GetIndexPartialView()
        {
            var steamNexusDbContext = _context.Games;
            return PartialView("_GameIndexManagementPartial", steamNexusDbContext);
        }

        //GameDataTable設定
        [HttpGet]
        public async Task<JsonResult> IndexJson()
        {
            return Json(_context.Games);
        }

        [HttpGet]
        public IActionResult GetCreatPartialView()
        {
            return PartialView("_GameCreateManagementPartial");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostCreatPartialToDB(CreateViewModel Create)
        {
            if (ModelState.IsValid)
            {
                Game game = new Game
                {
                    AppId = Create.AppId,
                    Name = Create.Name,
                    OriginalPrice = Create.OriginalPrice,
                    AgeRating = Create.AgeRating,
                    ReleaseDate = Create.ReleaseDate,
                    Publisher = Create.Publisher,
                    Description = Create.Description,
                    ImagePath = Create.ImagePath,
                    VideoPath = Create.VideoPath,
                };

                try
                {
                    _context.Games.Add(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    Console.WriteLine("錯誤");
                    if (!GameExists(game.GameId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return GetIndexPartialView();
            }


            return PartialView("_GameCreateManagementPartial", Create);
        }

        [HttpGet]
        public IActionResult GetEditPartialView(int id)
        {
            var game = _context.Games.FindAsync(id).Result;

            EditViewModel ViewModel = new EditViewModel
            {
                GameId = id,
                AppId = game.AppId,
                Name = game.Name,
                OriginalPrice = game.OriginalPrice,
                AgeRating = game.AgeRating,
                ReleaseDate = game.ReleaseDate,
                Publisher = game.Publisher,
                Description = game.Description,
                ImagePath = game.ImagePath,
                VideoPath = game.VideoPath
            };

            if (game == null)
            {
                return NotFound();
            }
            return PartialView("_GameEditManagementPartial", ViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostEditPartialToDB(EditViewModel ViewModel)
        {
            if (ModelState.IsValid)
            {
                var game = _context.Games.FindAsync(ViewModel.GameId).Result;
                game.GameId = ViewModel.GameId;
                game.AppId = ViewModel.AppId;
                game.Name = ViewModel.Name;
                game.OriginalPrice = ViewModel.OriginalPrice;
                game.AgeRating = ViewModel.AgeRating;
                game.ReleaseDate = ViewModel.ReleaseDate;
                game.Publisher = ViewModel.Publisher;
                game.Description = ViewModel.Description;
                game.ImagePath = ViewModel.ImagePath;
                game.VideoPath = ViewModel.VideoPath;

                try
                {
                    //_context.Entry(game).State = EntityState.Modified;
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    Console.WriteLine("錯誤");
                    if (!GameExists(game.GameId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return GetIndexPartialView();
            }
            //ViewData["MinReqId"] = new SelectList(_context.MinimumRequirements, "MinReqId", "MinReqId", game.MinReqId);
            //ViewData["RecReqId"] = new SelectList(_context.RecommendedRequirements, "RecReqId", "RecReqId", game.RecReqId);
            return PartialView("_GameEditManagementPartial", ViewModel);
        }

        [HttpGet]
        public IActionResult GetDetailsPartialView(int id)
        {

            var game = _context.Games
               .FirstOrDefaultAsync(m => m.GameId == id).Result;

            if (game == null)
            {
                return NotFound();
            }

            DetailsViewModel ViewModel = new DetailsViewModel
            {
                GameId = id,
                AppId = game.AppId,
                Name = game.Name,
                OriginalPrice = game.OriginalPrice,
                CurrentPrice = game.CurrentPrice,
                LowestPrice = game.LowestPrice,
                AgeRating = game.AgeRating,
                Comment = game.Comment,
                CommentNum = game.CommentNum,
                ReleaseDate = game.ReleaseDate,
                Publisher = game.Publisher,
                Description = game.Description,
                Players = game.Players,
                PeakPlayers = game.PeakPlayers,
                ImagePath = game.ImagePath,
                VideoPath = game.VideoPath
            };

            return PartialView("_GameDetailsManagementPartial", ViewModel);
        }

        [HttpGet]
        public IActionResult GetDeletePartialView(int id)
        {

            var game = _context.Games
                .FirstOrDefaultAsync(m => m.GameId == id).Result;

            if (game == null)
            {
                return NotFound(); // 或者根據您的需求返回其他值
            }

            DetailsViewModel ViewModel = new DetailsViewModel
            {
                GameId = id,
                AppId = game.AppId,
                Name = game.Name,
                OriginalPrice = game.OriginalPrice,
                CurrentPrice = game.CurrentPrice,
                LowestPrice = game.LowestPrice,
                AgeRating = game.AgeRating,
                Comment = game.Comment,
                CommentNum = game.CommentNum,
                ReleaseDate = game.ReleaseDate,
                Publisher = game.Publisher,
                Description = game.Description,
                Players = game.Players,
                PeakPlayers = game.PeakPlayers,
                ImagePath = game.ImagePath,
                VideoPath = game.VideoPath
            };


            return PartialView("_GameDeleteManagementPartial", ViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> PostDeletePartialToDB(int id)
        {
            var game = _context.Games.FindAsync(id).Result;
            if (game != null)
            {
                _context.Games.Remove(game);
            }

            await _context.SaveChangesAsync();

            return GetIndexPartialView();
        }


        private bool GameExists(int id)
        {
            return _context.Games.Any(e => e.GameId == id);
        }

        //(API)Game-Price抓取寫回程式庫(更新)
        [HttpGet]
        public async Task<string> GetGamePriceDataToDB()
        {
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Add("Accept-Language", "zh-TW");
            int? num = _context.Games.OrderByDescending(g => g.GameId).FirstOrDefault()?.GameId ?? 0;
            int allNum = 0;
            int errNum = 0;
            int priceErrNum = 0;
            try
            {
                for (int GameId = 10000; GameId <= num; GameId++)
                {
                    Console.WriteLine(GameId);
                    await Task.Delay(1400);

                    allNum++;
                    var game = await _context.Games.FindAsync(GameId);
                    PriceHistory PriceHistory = new PriceHistory
                    {
                        GameId = GameId
                    };

                    if (game == null)
                    {

SteamNexus/Areas/Administrator/Views/GamesManagement/_GameCreateManagementPartial.cshtml
@model SteamNexus.ViewModels.Game.CreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>新增遊戲</h1>

<hr />
<div class="row">
    <div class="justify-content-center">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
            <label asp-for="MinReqId" class="control-label"></label>
            <select asp-for="MinReqId" class ="form-control" asp-items="ViewBag.MinReqId"></select>
            </div>
            <div class="form-group">
            <label asp-for="RecReqId" class="control-label"></label>
            <select asp-for="RecReqId" class ="form-control" asp-items="ViewBag.RecReqId"></select>
            </div> *@
            <div class="form-group">
                <label asp-for="AppId" class="control-label"></label>
                <input asp-for="AppId" class="form-control text-center" />
                <span asp-validation-for="AppId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control text-center" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OriginalPrice" class="control-label"></label>
                <input asp-for="OriginalPrice" class="form-control text-center" />
                <span asp-validation-for="OriginalPrice" class="text-danger"></span>
            </div>
            @*  <div class="form-group">
            <label asp-for="CurrentPrice" class="control-label"></label>
            <input asp-for="CurrentPrice" class="form-control" />
            <span asp-validation-for="CurrentPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="LowestPrice" class="control-label"></label>
            <input asp-for="LowestPrice" class="form-control" />
            <span asp-validation-for="LowestPrice" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="AgeRating" class="control-label"></label>
                <input asp-for="AgeRating" class="form-control text-center" />
                <span asp-validation-for="AgeRating" class="text-danger"></span>
            </div>
            @* <div class="form-group">
            <label asp-for="Comment" class="control-label"></label>
            <input asp-for="Comment" class="form-control" />
            <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="CommentNum" class="control-label"></label>
            <input asp-for="CommentNum" class="form-control" />
            <span asp-validation-for="CommentNum" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control text-center" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="Publisher" class="form-control text-center" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea class="form-control text-center" id="Description" name="Description" rows="5">@Html.DisplayFor(modelItem => modelItem.Description)</textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @* <div class="form-group">
            <label asp-for="Players" class="control-label"></label>
            <input asp-for="Players" class="form-control" />
            <span asp-validation-for="Players" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="PeakPlayers" class="control-label"></label>
            <input asp-for="PeakPlayers" class="form-control" />
            <span asp-validation-for="PeakPlayers" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <img id="imgPreview" src="~/img/6306486.jpg" title="上無內容" style="width:250px;" /><br>
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control text-center" onchange="ImageChange(event)" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
                @*
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span> *@
            </div>
            <div class="form-group">
                <video id="videoPreview" width="250" controls autoplay muted src="#"></video><br>
                <label asp-for="VideoPath" class="control-label"></label>
                <input asp-for="VideoPath" class="form-control text-center" onchange="VideoChange(event)" />
                <span asp-validation-for="VideoPath" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <input id="PostCreatPartialToDB" type="submit" value="送出" class="btn btn-primary" />
            </div> *@
        </form>
       @*  <button class="btn btn-primary">
            <a asp-action="Index">回上一頁</a>
        </button> *@
    </div>
</div>

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<script src="~/js/site.js" asp-append-version="true"></script>
<script>
    function ImageChange(event) {
        previewImage(event.target.value, $("#imgPreview"))
    }
    function VideoChange(event) {
        previewVideo(event.target.value, $("#videoPreview"))
    }
    var baseAddress = "https://localhost:7097";
    $("#PostCreatPartialToDB").on("click", function (event) {

        event.preventDefault();
        $("#systemLoading").show();
        $.ajax({
            type: "POST",
            data: {
                AppId: Number($("#AppId").val()),
                Name: $("#Name").val(),
                OriginalPrice: Number($("#OriginalPrice").val()),
                AgeRating: $("#AgeRating").val(),
                ReleaseDate: $("#ReleaseDate").val(),
                Publisher: $("#Publisher").val(),
                Description: $("#Description").val(),
                ImagePath: $("#ImagePath").val(),
                VideoPath: $("#VideoPath").val()
            },
            url: `${baseAddress}@Url.Action("PostCreatPartialToDB", "Games")`
        }).done(data => {
                $("#systemLoading").hide();
                $("#System").html(data);
            })
            .fail(data => {
                $("#systemLoading").hide();
                $("#System").html(data);
            });
    });
</script>

SteamNexus/Areas/Administrator/Views/GamesManagement/_GameEditManagementPartial.cshtml
@model SteamNexus.ViewModels.Game.EditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>@Html.DisplayFor(modelItem => modelItem.Name)</h1>

<h4>遊戲編輯</h4>
<hr />
<div class="row">
    <div class="justify-content-center ">
        <form asp-controller="GamesManagement" asp-action="PostEditPartialToDB" asp-area="Administrator">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GameId" />
            @*             <div class="form-group">
            <label asp-for="MinReqId" class="control-label"></label>
            <select asp-for="MinReqId" class="form-control" asp-items="ViewBag.MinReqId"></select>
            <span asp-validation-for="MinReqId" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="RecReqId" class="control-label"></label>
            <select asp-for="RecReqId" class="form-control" asp-items="ViewBag.RecReqId"></select>
            <span asp-validation-for="RecReqId" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="AppId" class="control-label"></label>
                <input asp-for="AppId" class="form-control text-center" />
                <span asp-validation-for="AppId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control text-center" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OriginalPrice" class="control-label"></label>
                <input asp-for="OriginalPrice" class="form-control text-center" />
                <span asp-validation-for="OriginalPrice" class="text-danger"></span>
            </div>
            @*             <div class="form-group">
            <label asp-for="CurrentPrice" class="control-label"></label>
            <input asp-for="CurrentPrice" class="form-control" />
            <span asp-validation-for="CurrentPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="LowestPrice" class="control-label"></label>
            <input asp-for="LowestPrice" class="form-control" />
            <span asp-validation-for="LowestPrice" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="AgeRating" class="control-label"></label>
                <input asp-for="AgeRating" class="form-control text-center" />
                <span asp-validation-for="AgeRating" class="text-danger"></span>
            </div>
            @*             <div class="form-group">
            <label asp-for="Comment" class="control-label"></label>
            <input asp-for="Comment" class="form-control" />
            <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="CommentNum" class="control-label"></label>
            <input asp-for="CommentNum" class="form-control" />
            <span asp-validation-for="CommentNum" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control text-center" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="Publisher" class="form-control text-center" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea class="form-control text-center" id="Description" name="Description" rows="5">@Html.DisplayFor(modelItem => modelItem.Description)</textarea>
                @* <input asp-for="Description" class="form-control text-center" /> *@
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @*             <div class="form-group">
            <label asp-for="Players" class="control-label"></label>
            <input asp-for="Players" class="form-control" />
            <span asp-validation-for="Players" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="PeakPlayers" class="control-label"></label>
            <input asp-for="PeakPlayers" class="form-control" />
            <span asp-validation-for="PeakPlayers" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <img id="imgPreview" width="250" src="@Html.DisplayFor(modelItem => modelItem.ImagePath)" title="上無內容"/><br>
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" onchange="ImageChange(event)" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <video id="videoPreview" width="250" controls autoplay muted src="@Html.DisplayFor(modelItem => modelItem.VideoPath)"></video><br>
                <label asp-for="VideoPath" class="control-label"></label>
                <input asp-for="VideoPath" class="form-control" onchange="VideoChange(event)" />
                <span asp-validation-for="VideoPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input id="PostEditPartialToDB" name="@Html.DisplayFor(modelItem => modelItem.GameId)" type="submit" value="Save" class="btn btn-primary" style="display:none" onclick="submitonclick(event)" />
            </div>
        </form>
    </div>
</div>


@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

@* <div class="form-group">
    <a asp-action="Index">Back to List</a>
</div> *@
<script src="~/js/site.js" asp-append-version="true"></script>

@* <script>
    function ImageChange(event) {
        previewImage(event.target.value, $("#imgPreview"))
    }
    function VideoChange(event) {
        previewVideo(event.target.value, $("#videoPreview"))
    }
    $("#PostEditPartialToDB").on("click", function (event) {
        var num = event.target.name
        event.preventDefault();
        $("#systemLoading").show();
        $.ajax({
            type: "POST",
            data: {
                GameId: Number(num),
                AppId: Number($("#AppId").val()),
                Name: $("#Name").val(),
                OriginalPrice: Number($("#OriginalPrice").val()),
                AgeRating: $("#AgeRating").val(),
                ReleaseDate: $("#ReleaseDate").val(),
                Publisher: $("#Publisher").val(),
                Description: $("#Description").val(),
                ImagePath: $("#ImagePath").val(),
                VideoPath: $("#VideoPath").val()
            },
            url: `@Url.Action("PostEditPartialToDB", "GamesManagement", new { area = "Administrator" })`
        }).done(data => {
            console.log("已完成");
            $("#System").html(data);
        })
            .fail(data => {
                console.log("失敗");
                $("#systemLoading").hide();
                $("#System").html(data);
            });
    });
</script> *@