SteamNexus/Areas/Administrator/Controllers/MemberManagementController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SteamNexus.Data;
using SteamNexus.Models;
using SteamNexus.ViewModels.Game;
using System.ComponentModel.DataAnnotations;
using System.Text;
using static SteamNexus.Areas.Administrator.Controllers.MemberManagementController;
using static System.Net.Mime.MediaTypeNames;

namespace SteamNexus.Areas.Administrator.Controllers
{
    [Area("Administrator")]

    public class MemberManagementController : Controller
    {
        private readonly ILogger<MemberManagementController> _logger;
        private SteamNexusDbContext _application;
        private readonly IWebHostEnvironment _webHost;  //上傳圖片使用

        public MemberManagementController(SteamNexusDbContext application, IWebHostEnvironment webHostEnvironment, ILogger<MemberManagementController> logger)
        {
            _application = application;
            _webHost = webHostEnvironment;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult MemberManagement()
        {
            return PartialView("_MemberManagementPartial");
        }

        #region JsonUser資料
        public IActionResult MemberData()
        {
            var result = _application.Users.Select(result => new
            {
                result.Name,
                result.Email,
                Gender = result.Gender ? "男" : "女",
                birthday = result.Birthday.ToString(),
                result.Phone,
                result.Photo,

            });
            return Json(result);
        }
        #endregion


        #region JsonRolesName
        public JsonResult RolesData()
        {
            var result = _application.Roles.Select(result => new
            {
                result.RoleId,
                result.RoleName,
            });
            return Json(result);

        }
        #endregion


        #region Json結合User and Roles
        public IActionResult GetUsersWithRoles()
        {
            var result = _application.Users
                .Join(_application.Roles, u => u.RoleId, r => r.RoleId,
                (u, r) => new
                {
                    UserId = u.UserId,
                    Name = u.Name,
                    Email = u.Email,
                    Gender = u.Gender ? "男" : "女",
                    Birthday = u.Birthday.ToString(),
                    Phone = u.Phone,
                    Photo = u.Photo,
                    RoleName = r.RoleName,
                });

            return Json(result);
        }
        #endregion


        #region 會員資料刪除無刪除圖片
        //[HttpPost]
        //public async Task<IActionResult> DeleteUser(int id)
        //{
        //    try
        //    {
        //        var user = await _application.Users.FindAsync(id);
        //        if (user == null)
        //        {
        //            // 加入調試信息，確認ID值和數據庫內是否匹配
        //            return Json(new { success = false, message = "用戶未找到，ID: " + id });
        //        }

        //        _application.Users.Remove(user);
        //        await _application.SaveChangesAsync();
        //        return Json(new { success = true, message = "用戶已刪除" });
        //    }
        //    catch (Exception ex)
        //    {
        //        //記錄錯誤
        //        return Json(new { success = false, message = ex.Message });
        //    }
        //}
        #endregion


        #region 會員資料刪除並移除圖片

        [HttpPost]
        public async Task<IActionResult> DeleteUser(int id)
        {
            try
            {
                var user = await _application.Users.FindAsync(id);
                if (user == null)
                {
                    // 加入調試信息，確認ID值和數據庫內是否匹配
                    return Json(new { success = false, message = "用戶未找到，ID: " + id });
                }

                // 刪除用戶的圖片
                if (!string.IsNullOrEmpty(user.Photo) && user.Photo != "default.jpg")
                {
                    var filePath = Path.Combine(_webHost.WebRootPath, "images/headshots", user.Photo);
                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }
                }

                _application.Users.Remove(user);
                await _application.SaveChangesAsync();
                return Json(new { success = true, message = "用戶已刪除" });
            }
            catch (Exception ex)
            {
                //記錄錯誤
                return Json(new { success = false, message = ex.Message });
            }
        }
        #endregion


        #region EditViewModel
        public partial class EditUserViewModel
        {
            [Required]
            public int UserId { get; set; }

            [Required]
            public string RoleName { get; set; }


            [Required]
            [MaxLength(100)]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [MaxLength(50)]
            public string Name { get; set; }

            public bool Gender { get; set; } = true;

            #nullable enable
            [MaxLength(10)]
            [RegularExpression(@"^09\d{8}$", ErrorMessage = "手機號碼必須以09開頭並且是10位數字")]
            [Required(ErrorMessage = "請輸入手機號碼")]
            public string? Phone { get; set; }

            [Display(Name = "生日")]
            [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)] // 指定日期的顯示格式
            public DateTime? Birthday { get; set; }


            public IFormFile? Photo { get; set; }

        }
        #endregion


        #region 修改資料更新成功無圖片
        //[HttpPost]
        //public async Task<ActionResult> EditUser([FromForm] EditUserViewModel data)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var user = await _application.Users
        //                    .Include(u => u.Role)
        //                    .FirstOrDefaultAsync(u => u.UserId == data.UserId);

        //        if (user == null)
        //        {
        //            return NotFound($"無法找到ID為 {data.UserId} 的用戶。");
        //        }

        //        user.UserId = data.UserId;
        //        user.Name = data.Name;
        //        user.Email = data.Email;
        //        user.Phone = data.Phone;
        //        user.Gender = data.Gender;
        //        user.Birthday = data.Birthday;

        //        // 查找新的角色ID
        //        var newRole = await _application.Roles.FirstOrDefaultAsync(r => r.RoleName == data.RoleName);
        //        if (newRole != null && newRole.RoleId != user.RoleId)
        //        {
        //            user.RoleId = newRole.RoleId;
        //        }

        //        await _application.SaveChangesAsync();
        //        TempData["SuccessMessage"] = "用戶資料已成功更新。";
        //        return RedirectToAction("MemberManagement");  // 或其他適當的成功頁面
        //    }
        //    return View(data);  // 返回表單與驗證錯誤
        //}

        #endregion


        #region 修改資料
        [HttpPost]
        public async Task<ActionResult> EditUser([FromForm] EditUserViewModel data)
        {
            if (ModelState.IsValid)
            {
                var user = await _application.Users
                            .Include(u => u.Role)  // 使用 Include 載入相關的角色資料
                            .FirstOrDefaultAsync(u => u.UserId == data.UserId);

                if (user == null)
                {
                    return NotFound($"無法找到ID為 {data.UserId} 的用戶。");
                }

                user.UserId = data.UserId;
                user.Name = data.Name;
                user.Email = data.Email;
                user.Phone = data.Phone;
                user.Gender = data.Gender;
                user.Birthday = data.Birthday;

                // 查找新的角色ID
                var newRole = await _application.Roles.FirstOrDefaultAsync(r => r.RoleName == data.RoleName);
                if (newRole != null && newRole.RoleId != user.RoleId)
                {
                    user.RoleId = newRole.RoleId;  // 只在角色有變化時更新角色ID
                }

                // 處理檔案上傳，沒有預設圖片
                //if (data.Photo != null && data.Photo.Length > 0)
                //{
                //    // 刪除舊的圖片
                //    if (!string.IsNullOrEmpty(user.Photo))
                //    {
                //        var oldFilePath = Path.Combine(_webHost.WebRootPath, "images/headshots", user.Photo);
                //        if (System.IO.File.Exists(oldFilePath))
                //        {
                //            System.IO.File.Delete(oldFilePath);
                //        }
                //    }

                //    // 儲存新的圖片
                //    string filename = Guid.NewGuid().ToString() + Path.GetExtension(data.Photo.FileName);
                //    string uploadfolder = Path.Combine(_webHost.WebRootPath, "images/headshots");
                //    string filepath = Path.Combine(uploadfolder, filename);

                //    using (var fileStream = new FileStream(filepath, FileMode.Create))
                //    {
                //        await data.Photo.CopyToAsync(fileStream);
                //    }

                //    user.Photo = filename;
                //}

                if (data.Photo != null && data.Photo.Length > 0)
                {
                    // 刪除舊的圖片，除非它是預設圖片
                    if (!string.IsNullOrEmpty(user.Photo) && user.Photo != "default.jpg")
                    {
                        var oldFilePath = Path.Combine(_webHost.WebRootPath, "images/headshots", user.Photo);
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }

                    // 儲存新的圖片

SteamNexus/Areas/Administrator/Views/MemberManagement/RolesData.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SteamNexus/Areas/Administrator/Views/MemberManagement/_createRolePartial.cshtml
@* PartialView 的 CSS *@
<link href="~/css/hardwareproductmanagesystem.css" rel="stylesheet" asp-append-version="true" />

<style>
    .valid-feedback {
        color: green;
        display: none;
        /* 預設不顯示，除非添加此類 */
    }

    .invalid-feedback {
        color: red;
        display: none;
        /* 預設不顯示，除非添加此類 */
    }

</style>

@* PartialView 的 HTML *@
<div class="page-title position-relative">
    <div class="row">
        @* 系統名稱 *@
        <div class="col-12 col-md-6 order-md-1 d-flex justify-content-center justify-content-md-start">
            <h2 id="SystemName" style="margin-top: 8px;">權限管理系統</h2>
        </div>
        @* 系統選單 *@
        <div class="col-12 col-md-6 order-md-2 d-flex justify-content-center justify-content-md-end" id="SystemMenu">
            @*             <select asp-items="@ViewBag.ComputerParts" class="form-select " style="width:250px;height:40px;margin-bottom:8px" id="HardSelect">
            <option value="" disabled selected hidden>---- 請選擇硬體 ----</option>
            </select> *@
            <button class="btn btn-danger" id="createRoles">新增權限</button>
        </div>
            
    </div>
</div>

@* Datatables設定 *@
<section class="section">
    <table id="RolesManageTable" class="display" style="width:100%" ;>
        <thead id="HardwareThead">
            <tr>
                <th data-priority="1">編號</th>
                <th>名稱</th>
                <th>刪除</th>
            </tr>
        </thead>
    </table>
</section>

@* 新增權限的浮動式窗 *@
<div class="modal fade" id="createrole" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">新增權限</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="createRoles">
            <div class="input-group input-group-lg mb-3">
                <span class="input-group-text" id="inputGroup-sizing-lg" style="color:white">權限名稱：</span>
                <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" id="Roles_name" pattern="[A-Za-z]+" title="只能輸入大小寫英文">
                <div id="rolesFeedback" class="invalid-feedback"></div>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="crate">新增</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="crateroles">關閉視窗</button>
      </div>
    </div>
  </div>
</div>


@* Toast 彈出式通知 容器 start *@
<div class="position-fixed top-0 start-50 translate-middle-x p-3" style="z-index: 11" id="ToastContainer">
</div>
@* Toast 彈出式通知 容器 end *@
@* 防偽標籤 生成(會是個 input hidden 元素) *@
@Html.AntiForgeryToken();
@*
    目的: 防止 CSRF 攻擊
    也會生成兩個 cookie => HttpOnly=true、SameSite=Strict
    AntiforgeryCookie => 存的是 防偽標籤 值
    .AspNetCore.Antiforgery.名稱 => 存的是 防偽標籤的 名稱
*@
@* PartialView 的 JavaScript *@
<script>
    $(document).ready(function () {
        let HardAddress = "https://localhost:7097";

        // 初始化 Datatables
        var datatable = new DataTable('#RolesManageTable', {
            ajax: {
                type: "GET",
                url: `@Url.Action("RolesData", "MemberManagement", new { area = "Administrator" })`,
                dataSrc: function (json) { return json; }
            },
            // column 定義
            columns: [
                { "data": "roleId", "width": "10%", "className": "text-center" },
                { "data": "roleName", "width": "10%", "className": "text-center" },
                {
                    "data": null,
                    "orderable": false,
                    "width": "10%",
                    "className": "text-center",
                    render: function (data, type, row, meta) {
                        // 取得 roleId
                        let RoleId = row.roleId;
                        let RoleName = row.roleName;
                        // 刪除按鈕
                        let resetEle = `<button class="btn btn-danger del-btn" data-roleid="${row.roleId}" data-rolename="${RoleName}" data-bs-toggle="popover" data-bs-content="nothing"><i class="bi bi-trash3-fill"></i></button>`;


                        if (type === 'display') {
                            return `${resetEle}`;
                        }
                        return data;
                    }, responsivePriority: 1
                },
            ],
            // 標頭固定
            fixedHeader: {
                // 固定 header
                header: true,
                // 使用導覽欄的高度作為偏移量
                headerOffset: $('#pageNav').outerHeight(),
            },
            // 響應式設計
            responsive: true,
            // 語言設定
            language: {
                url: '//cdn.datatables.net/plug-ins/2.0.3/i18n/zh-HANT.json',
            },
            // 預設排序 ~ 根據第一個欄位 升冪排序
            order: [[1, 'asc']],
            // 自動寬度 關閉
            autoWidth: true,

        });

        // 顯示窗口
        $(document).on('click', '#createRoles', function () {
            $('#createrole').modal('show');
        });

        //確認權限是否存在，如以存在會即時顯示通知
        // $(document).ready(function () {
        //     $('#Roles_name').on('input', function () {
        //         var rolename = $(this).val();
        //         if (rolename) {
        //             $.ajax({
        //                 url: '@Url.Action("CheckRolesExists", "MemberManagement", new { area = "Administrator" })',  // 確保路徑正確
        //                 data: { roleName: rolename },
        //                 method: 'GET',
        //                 success: function (isAvailable) {
        //                     var feedbackElement = $('#rolesFeedback');
        //                     if (isAvailable) {
        //                         feedbackElement.text('此權限可以使用').removeClass('invalid-feedback').addClass('valid-feedback');
        //                         $('#Roles_name').removeClass('is-invalid').addClass('is-valid');
        //                         $('#crate').prop('disabled', false);
        //                     } else {
        //                         feedbackElement.text('該權限已被使用，請更換權限').removeClass('valid-feedback').addClass('invalid-feedback');
        //                         $('#Roles_name').removeClass('is-valid').addClass('is-invalid');
        //                         $('#crate').prop('disabled', true);
        //                     }
        //                     feedbackElement.show();  // 確保提示信息顯示
        //                 },
        //                 error: function () {
        //                     $('#rolesFeedback').text('無法檢查權限').addClass('invalid-feedback');
        //                     $('#rolesFeedback').show();
        //                     $('#crate').prop('disabled', true);
        //                 }
        //             });
        //         } else {
        //             $('#rolesFeedback').hide();  // 當 RoleName 欄位為空時，不顯示任何反饋
        //             $('#crate').prop('disabled', true);
        //         }
        //     });
        // });


        //檢查權限是否存在與使用者輸入是否為英文大小寫
        $(document).ready(function () {
            $('#Roles_name').on('input', function () {
                var rolename = $(this).val();
                var feedbackElement = $('#rolesFeedback');
                // 使用正則表達式檢查是否僅包含英文大小寫字母
                var isValidEnglish = /^[A-Za-z]+$/.test(rolename);

                // 首先判斷是否為空，如果為空則隱藏所有提示並禁用按鈕
                if (rolename === '') {
                    feedbackElement.text('').hide();
                    $('#Roles_name').removeClass('is-valid is-invalid');
                    $('#create').prop('disabled', true);
                } else if (!isValidEnglish) {
                    // 如果不是空但輸入非英文，顯示錯誤信息
                    feedbackElement.text('請輸入英文大小寫').removeClass('valid-feedback').addClass('invalid-feedback');
                    $('#Roles_name').removeClass('is-valid').addClass('is-invalid');
                    $('#create').prop('disabled', true);
                    feedbackElement.show();
                } else {
                    // 如果輸入僅包含英文，則進行 AJAX 請求檢查角色名稱是否存在
                    $.ajax({
                        url: '@Url.Action("CheckRolesExists", "MemberManagement", new { area = "Administrator" })',
                        data: { roleName: rolename },
                        method: 'GET',
                        success: function (isAvailable) {
                            if (isAvailable) {
                                feedbackElement.text('此角色可以使用').removeClass('invalid-feedback').addClass('valid-feedback');
                                $('#Roles_name').removeClass('is-invalid').addClass('is-valid');
                                $('#create').prop('disabled', false);
                            } else {
                                feedbackElement.text('該角色已被使用，請更換角色名稱').removeClass('valid-feedback').addClass('invalid-feedback');
                                $('#Roles_name').removeClass('is-valid').addClass('is-invalid');
                                $('#create').prop('disabled', true);
                            }
                            feedbackElement.show();
                        },
                        error: function () {
                            feedbackElement.text('無法檢查角色').addClass('invalid-feedback');
                            feedbackElement.show();
                            $('#create').prop('disabled', true);
                        }
                    });
                }
            });
        });


        //新增權限
        $(document).on('click', '#crate', function () {
            // 收集表單數據
            var roleName = $('#Roles_name').val();

            // 檢查輸入是否為空
            if (roleName === '') {
                alert('請輸入權限名稱');
                return;
            }

            // 創建 POST 請求的數據對象
            var postData = {
                RoleName: roleName
            };

            // 發送 AJAX 請求
            $.ajax({
                url: '/Administrator/MemberManagement/CreateRole', // 修改為實際的 URL 路徑
                type: 'POST',
                data: postData,
                success: function (response) {
                    // 處理回應
                    if (response.success) {
                        alert('新增成功');
                        $('#createrole').modal('hide'); // 關閉模態窗口
                        // 重新加載或更新 DataTable
                        $('#RolesManageTable').DataTable().ajax.reload();
                    } else {
                        alert('新增失敗: 請輸入英文大小寫');
                    }
                },
                error: function (xhr, status, error) {
                    // 使用更詳細的錯誤信息
                    alert('請求失敗: ' + xhr.responseText);
                }
            });
        });


        //刪除權限
        $(document).on('click', '.del-btn', function () {
            const roleId = $(this).data('roleid');
            console.log("Deleting Role ID:", roleId);
        
            $.ajax({
                url: '/Administrator/MemberManagement/DeleteRole',
                type: 'POST',
                data: {
                    id: roleId, // 確保這裡使用正確的參數名稱
                    __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val() //防偽標記
                },
                success: function (response) {
                    if (response.success) {
                        alert('刪除成功');
                        $('#RolesManageTable').DataTable().ajax.reload();
                    } else {
                        alert('刪除失敗: ' + response.message);
                    }
                },
                error: function (error) {
                    alert('發生錯誤: ' + error.responseText);
                }
            });
        });


        //點擊關閉視窗重製資料
        $(document).ready(function () {
            $('button[data-bs-dismiss="crateroles"]').click(function () {
                resetForm();
            });

            // 綁定 ESC 鍵到 document，按下時執行重置表單
            $(document).keydown(function (e) {
                if (e.keyCode == 27) {  // 27 是 ESC 鍵的鍵盤代碼
                    resetForm();
                }
            });

            // 重置表單
            function resetForm() {
                $('#Roles_name').val('');
                $('#rolesFeedback').text('').hide();
                $('#Roles_name').removeClass('is-valid is-invalid');

                // 隱藏模態窗口
                $('#createrole').modal('hide');
            }


        });

    });
</script>